### ISSUE TITLE
I am not receiving more information and still dont know the problem

### ISSUE THREAD

**Issue by emilianochiozzi** [capistrano-plugins/capistrano-ssh-doctor#3]
![screen shot 2015-03-02 at 6 10 10 pm](https://cloud.githubusercontent.com/assets/2271199/6450577/8956f7b0-c107-11e4-8a82-2af1a45dd227.png)

Hi Bruno, nice job in this gem.
This what I get running this tool. I am using a .pem autentication file. But I don't even know if it is finding the file. Could you help me please?

**Comment by bruno-** [comment]
Hey, thanks for opening an issue. A user is not supposed to ever get that output, so, that's a bug :)

I suppose you know the path to your `.pem` file?
Do you have the path to the key set in `ssh_options` [as shown here](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/templates/stage.rb.erb#L42-L48)?

From your output, it seems the key that is being used is "/users/emilianochiozzi/.ssh/id_rsa". That's not the key you want to use, right?

**Comment by bruno-** [comment]
Even easier, you can specify the key like this:

    server "111.112.113.114", user: "deploy", roles: %w{web app db}, keys: "/foo/bar.pem"

Also, I've opened issues #4 and #5 based on your report.
Let me know if the above works for you?

If not, maybe the solution is to add the "custom" `.pem` key to your local ssh agent. Old school instructions how to do that [here](http://sshkeychain.sourceforge.net/mirrors/SSH-with-Keys-HOWTO/SSH-with-Keys-HOWTO-6.html)

**Comment by emilianochiozzi** [comment]
I will try this. Thanks!

**Comment by bruno-** [comment]
Did this work?

**Comment by emilianochiozzi** [comment]
Yes! It worked. Thanks
