### ISSUE TITLE
Please change `scm` setting to `:git`.

### ISSUE THREAD

**Issue by cyclingzealot** [capistrano-plugins/capistrano-ssh-doctor#9]
Running ssh:doctor, I get:

```
$ bundle exec cap staging ssh:doctor
It seems you are NOT using git as a Capistrano strategy. At the moment capistrano-ssh-doctor supports only git.
Please change `scm` setting to `:git`.
```

If I add to my ```deploy.rb``` file:

`
set :scm, :git
`

I get 

```
lusk 16:46:32 {12408_deployLearning} ~/code/sg6$ bundle exec cap staging ssh:doctor
[Deprecation Notice] `set :scm, :git` is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile after
`require "capistrano/deploy"`:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git

It seems you are NOT using git as a Capistrano strategy. At the moment capistrano-ssh-doctor supports only git.
Please change `scm` setting to `:git`.


```

Using cap 3.9.0:

```
$ cap -v
Capistrano Version: 3.9.0 (Rake Version: 12.0.0)

```

**Comment by exocode** [comment]
Have the same issue same cap version

Capistrano Version: 3.9.0 (Rake Version: 12.0.0)

**Comment by exocode** [comment]
till this pull request is merged you can try/use my branch:

  gem 'capistrano-ssh-doctor', git: 'https://github.com/exocode/capistrano-ssh-doctor.git', branch: 'exocode-patch-1', require: false, group: :development

**Comment by exocode** [comment]
it seems not be the end of the road. We also must keep in mind that the strategy.check has removed completely with 3.9

**Comment by bruno-** [comment]
@exocode Since I haven't used ssh-doctor in a while I've invited you to be the admin of this repo.

**Comment by pboling** [comment]
Looks like it is as simple as editing the rake task in the gem to remove the `strategy.check`

**Comment by pboling** [comment]
This is fixed, and can be closed, @exocode
